[project]
name = "sc4020-project2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.3.0",
    "mlxtend>=0.23.4",
    "pandas>=2.3.3",
]

[dependency-groups]
dev = [
    "ruff>=0.14.2",
]
